# This workflow adds documents to the Rockset collections when a change is made

name: Add compendium entries

on:
  push:
      branches:
        - master
      paths:
        - 'compendium/*.json'

jobs:
  main:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
            sudo npm install -g @rockset/cli
      - name: Authorize access
        run: |
          rockset auth:add me ${{ secrets.RS2_TOKEN }}
      - name: Add docs
        run: |
          source .github/workflows/add-compendium-entries/main.sh