# Execute API tests in tests/

name: API Tests

on: push

jobs:
  main:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [15.x]
          python-version: ["3.6"]
      steps:
      - uses: actions/checkout@v2
      - name: Start API server
        run: |
            sudo pip3 install -r requirements.txt
            sudo pip3 install protobuf
            python3 server.py & ${{ secrets.RS2_TOKEN }}
      - name: Install dependencies
        run: |
            cd tests
            npm i 
            sudo npm i -g mocha 
            sudo npm i -g ts-node
            sudo npm i typescript
      - name: Execute tests
        run: |
            pwd
            cd tests
            pwd
            env URL="http://127.0.0.1:5000/api/v2" mocha test/index.ts -r ts-node/register